2019-06-14 15:05:29 , Error: Error in `[<-`(`*tmp*`, i, , value = unlist(lapply(group_chars, species_percentage_match, : subscript out of bounds

2019-06-14 15:59:13 , Error: Error in cmdscale(dist, k = k): NA values not allowed in 'd'

2019-06-14 17:48:00 , Error: Error in is_character(x): object 'X' not found

2019-06-14 17:50:07 , Error: Error in is_character(x): object 'X' not found

2019-06-14 17:50:46 , Error: Error in is_character(x): object 'X' not found

2019-06-14 18:08:52 , Error: Error in is_character(x): object 'X' not found

2019-06-14 18:20:26 , Error: Error in is_character(x): object 'X' not found

2019-06-14 18:21:13 , Error: Error in is_character(x): object 'X' not found

2019-06-14 18:23:15 , Error: Error in is_character(x): object 'X' not found

2019-06-14 18:32:13 , Error: Cell data  25, 93  have no data.
2019-06-14 18:33:25 , Error: Cell data  25, 93  have no data.
2019-06-14 18:36:41 , Error: Cell data  93  have no data.
2019-06-14 18:37:19 , Error: Error in if (check_infile()$env_present) {: argument is of length zero

2019-06-14 18:37:35 , Error: Error in if (check_infile()$env_present) {: argument is of length zero

2019-06-14 18:39:00 , Error: Error in if (check_infile()$env_present) {: argument is of length zero

2019-06-14 18:39:30 , Error: Cell data  93  have no data.
2019-06-14 21:24:38 , Error: Cells  93  have no data.
2019-06-14 21:32:37 , Error: Cells  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 21:35:36 , Error: Error in is_character(x): object 'X' not found

2019-06-14 21:50:04 , Error: Error in is_character(x): object 'X' not found

2019-06-14 21:53:44 , Error: Error in is_character(x): object 'X' not found

2019-06-14 22:17:11 , Error: Error in is_character(x): object 'X' not found

2019-06-14 22:22:59 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 22:27:17 , Error: Error in is_character(x): object 'X' not found

2019-06-14 22:39:10 , Error: Error in is_character(x): object 'X' not found

2019-06-14 22:54:50 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 22:57:08 , Error: Error in is_character(x): object 'X' not found

2019-06-14 22:58:28 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 22:58:30 , Error: Error in is_character(x): object 'X' not found

2019-06-14 23:03:04 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 23:03:13 , Error: Error in is_character(x): object 'X' not found

2019-06-14 23:03:32 , Error: Error in is_character(x): object 'X' not found

2019-06-14 23:04:30 , Error: Row(s)  87, 88, 89, 90  have no species for their respective sites. file:VegClassTeamTestData_SitexSpMatrix_NoEnvVars.csv
2019-06-14 23:22:31 , Error: Error in str_split(toString(allfiledata[1]), ","): could not find function "str_split"

2019-06-14 23:23:24 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2019-06-14 23:23:35 , Error: Uploaded data file is not comma separated. Please check acceptable file formats. file:KT_TestData_SitexSpMatrix_WithEnvVars_TAB.txt
2019-06-21 21:51:43 , Error: data is incorrect format. Check sample data for correct format. file:DummyPCTIDToolDataInputFormatNOX.csv
2019-06-21 21:51:56 , Error: Cell(s)  93  have no data. file:KT_TestData_SitexSpMatrix_WithEnvVars_BLANK_DATA.txt
2022-06-22 15:07:17 , Error: Error in s[[1]][[i]]: subscript out of bounds

2022-06-22 15:09:45 , Error: Error in s[[1]][[i]]: subscript out of bounds

2022-06-22 15:16:09 , Error: Error in s[[1]][[i]]: subscript out of bounds

2022-06-23 14:34:30 , Error: Error in s[[1]][[i]]: subscript out of bounds

2023-12-01 09:16:04 , Error: Error: Columns `TEC_Comments` not found

2023-12-01 09:20:13 , Error: Error: Columns `TEC_Comments` not found

2023-12-01 09:34:28 , Error: Error: near "A": syntax error

2023-12-01 09:55:50 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-08 17:54:13 , Error: [1m[33mError[39m in `between()` at ]8;line = 239:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:239:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 17:58:16 , Error: [1m[33mError[39m in `between()` at ]8;line = 239:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:239:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 17:59:19 , Error: [1m[33mError[39m in `between()` at ]8;line = 239:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:239:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 18:00:11 , Error: [1m[33mError[39m in `between()` at ]8;line = 239:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:239:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 18:01:15 , Error: [1m[33mError[39m in `between()` at ]8;line = 239:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:239:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 18:08:02 , Error: [1m[33mError[39m in `between()` at ]8;line = 237:col = 5;file://C:\Users\magaree\PlotToPCTIDTool\vegplot\server.RC:\Users\magaree\PlotToPCTIDTool\vegplot/server.R:237:5]8;;:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 18:08:44 , Error: [1m[33mError[39m in `between()`:[22m
[33m![39m Can't combine `x` <data.frame> and `left` <double>.

2023-12-08 23:52:04 , Error: Cell(s)  6  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:Error1ValueOutOfCARange_ShinyTest_SiteXSpeciesMatrix_WithEnvVars.csv
2023-12-08 23:55:54 , Error: Cell(s)  6  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:Error1ValueOutOfCARange_ShinyTest_SiteXSpeciesMatrix_WithEnvVars.csv
2023-12-08 23:56:28 , Error: Cell(s)  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:8625_EM_TestCUMBSurveyExport.csv
2023-12-08 23:57:20 , Error: Cell(s)  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:8625_EM_TestCUMBSurveyExport.csv
2023-12-09 00:54:08 , Error: Cell(s)  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:8625_EM_TestCUMBSurveyExport.csv
2023-12-09 00:54:26 , Error: Cell(s)  6  have data with values outside cover-abundance score range (range = 0-6 inclusive) file:Error1ValueOutOfCARange_ShinyTest_SiteXSpeciesMatrix_WithEnvVars.csv
2023-12-15 12:17:57 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-15 12:18:42 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-15 12:26:09 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-15 12:29:25 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-15 12:54:57 , Error: Error in open.connection(con, "rb"): cannot open the connection

2023-12-15 13:49:21 , Error: Error in if (is.na(d1$Classification_confidence_level)) "" else d1$Classification_confidence_level: argument is of length zero

2023-12-15 13:49:51 , Error: Error in if (is.na(d1$Classification_confidence_level)) "" else d1$Classification_confidence_level: argument is of length zero

2023-12-15 13:50:03 , Error: Error in if (is.na(d1$Classification_confidence_level)) "" else d1$Classification_confidence_level: argument is of length zero

2024-09-20 09:45:24 , Error: Error in open.connection(con, "rb"): cannot open the connection

2024-09-20 10:13:41 , Error: Error in open.connection(con, "rb"): cannot open the connection

2024-09-23 07:51:49 , Error: Error in if (is.na(d1$Classification_confidence_level)) "" else d1$Classification_confidence_level: argument is of length zero

